# Generated by Django 3.0.6 on 2020-06-17 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_auto_20200602_0450'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lignefacture',
            name='produit-facture',
        ),
        migrations.AlterField(
            model_name='facture',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facture_client', to='bill.Client'),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_facture', to='bill.Facture'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='fournisseur',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fournisseur_produit', to='bill.Fournisseur'),
        ),
        migrations.AddConstraint(
            model_name='lignefacture',
            constraint=models.UniqueConstraint(fields=('produit', 'facture'), name='produit_facture'),
        ),
    ]
